### ISSUE TITLE
error

### ISSUE THREAD

**Issue by studybug** [learn-co-curriculum/python-dictionaries-lab#6]
Code is not working.  I go in to fill out the worksheet but notebook does not understand:

greenville
greenville_population = greenville[3]
greenville_population

KeyErrorTraceback (most recent call last)
<ipython-input-5-2893edf7c02f> in <module>()
----> 1 greenville_population = greenville[-1]
      2 greenville_population

KeyError: -1

Now retrieve the area of Greenville and assign it to the variable greenville_area.

greenville_area = greenville[0]
greenville_area # 68
Now let's take a look at all of the keys in the greenville dictionary and coerce them into a list. Assign this variable to the list city_keys.

**Comment by LoreDirick** [comment]
Hi @studybug:
greenville is not a list, but a dictionary. Hence the correct call is:

`greenville['Population']`

You'll see that this will correctly return 84554.
