### ISSUE TITLE
Python Dictionaries Lab, PyeongChang type and list problem (w/ my resolution)

### ISSUE THREAD

**Issue by harrisonhardin** [learn-co-curriculum/python-dictionaries-lab#7]
After assigning the correct command to display both the values and then keys of the dictionary item PyeongChang, I couldn't find any way to get the desired output. It would only output the second command in each, the type() command, outputting "list." My resolution was to create a new python Jupyter box (with 'b') for the type() commands and this solved it, but I want to know how to solve it without doing this additional step. Here is what it looked like:

In: 
pyeongchang_values = list(cities[11].values())
pyeongchang_values # ['PyeongChang', 'South Korea', 2581000, 3194]
Out:
['PyeongChang', 'South Korea', 2581000, 3194]

In:
type(pyeongchang_values) # list
Out:
list

In:
pyeongchang_keys = list(cities[-1].keys())
pyeongchang_keys # ['City', 'Country', 'Population', 'Area']
Out: 
['City', 'Country', 'Population', 'Area']

In:
type(pyeongchang_keys) # list
Out:
list

**Comment by mas16** [comment]
Hi harrisonhardin, we have implemented your approach. Thank you for bringing the issue to our attention.
