### ISSUE TITLE
Intro to Python > Python Collections > Python Dictionaries Lab

### ISSUE THREAD

**Issue by perickson91** [learn-co-curriculum/python-dictionaries-lab#8]
![Capture](https://user-images.githubusercontent.com/47877539/54092205-bb02fc80-435f-11e9-833b-bc31b6ae5cc8.JPG)

I believe my response is correct. I'm second guessing because the solution suggests the 'Area' as the first key on this list. Was the excel sheet adjusted and the solution not updated?

Please point out my mistake if I am incorrect. 

Thanks,
Peter

**Comment by KimoonRyu** [comment]
I Agree!
![image](https://user-images.githubusercontent.com/50130361/56995770-a9c0ba00-6b70-11e9-8ebb-58e6970b4240.png)

**Comment by mas16** [comment]
Hi there! Python dictionaries were originally not guaranteed to be in a specific order. What is important is that the corresponding key/value pairs are the same. In newer versions of Python (3.6+), dictionaries were switched to be ordered by default. The solution comment has been updated. Thank you for raising this issue!
